### ISSUE TITLE
Missing credit and license

### ISSUE THREAD

**Issue by huhenU** [team-mercure/mercury#14]
Hello,
your pack is missing credits and license for sept as well as included sysmodules. Please fix

**Comment by gaavin** [comment]
it credits reinx which credits Sept which credits all sysmodules of the universe

**Comment by dennieh** [comment]
That's right, sadly ReiNX is under the GPLv2 license which requires you to release the source alongside your binaries. This means your License is invalid and your repo is therefore violating not only ReiNX's license but also the included Atmosphere code.
![image](https://user-images.githubusercontent.com/47433458/61581849-0a361680-ab24-11e9-8e7e-6dc70a217c28.png)

Even if ReiNX was properly credited, ReiNX only credits the Atmosphere sysmodules that are used - not sept which you are using

**Comment by gaavin** [comment]
the source is identical and their GitHub repos are linked. This is just a package containing their binaries from the release page

**Comment by gaavin** [comment]
The source doesn't need to be distributed I'd it isn't modified

**Comment by dennieh** [comment]
"their source is identical" is not a valid argument against license violation though.
All you have to do is properly add the source for the ReiNX files you use (you can do that with a submodule/subrepo) + add credits to Atmosphere for the sept binaries

**Comment by dennieh** [comment]
"For example, if you distribute copies of such a program, whether
gratis or for a fee, you must give the recipients all the rights that
you have.  You must make sure that they, too, receive or can get the
source code."

From only your repo i'm not able to get the source for sept i fear

**Comment by gaavin** [comment]
your argument doesn't make any sense because all sources are properly linked and credited. If your issue is with reinx not crediting Sept then go complain there instead

**Comment by NovaPhoenix** [comment]
You are obligated to read the entire GPLv2 license by releasing something which includes GPLv2 code, please do so as soon as possible.  https://choosealicense.com/licenses/gpl-2.0/

**Comment by zilrich** [comment]
he has linked the source code. it doesn't need to be in the same repo.
