### ISSUE TITLE
You have small penis

### ISSUE THREAD

**Issue by SirVertigo** [team-mercure/mercury#16]
Do you remember, 21st night of September? 
Love was changing the mind of pretenders 
While chasing the clouds away 
Our hearts were ringing 
In the key that our souls were singing 
As we danced in the night 
Remember, how the stars stole the night away 
Hey hey hey 
Ba de ya, say that you remember 
Ba de ya, dancing in September 
Ba de ya, never was a cloudy day 
Ba duda, ba duda, ba duda, badu 
Ba duda, badu, ba duda, badu 

Ba duda, badu, ba duda, yeah 
My thoughts are with you 
Holding hands with your heart to see you 
Only blue talk and love 
Remember, how we knew love was here to stay 
Now December 
Found the love we shared in September 
Only blue talk and love 
Remember, the true love we share today 
Hey hey hey 
Ba de ya, say that you remember 
Ba de ya, dancing in September 
Ba de ya, never was a cloudy day 
There was a 
Ba de ya, say that you remember 
Ba de ya, dancing in September 
Ba de ya, golden dreams were shiny days 
Now our bell was ringing, aha 
Our souls was singing 
Do you remember every cloudy day, yau 
There was a 
Ba de ya, say that you remember 
Ba de ya, dancing in September 
Ba de ya, never was a cloudy day 
There was a 
Ba de ya, say that you remember 
Ba de ya, dancing in September 
Ba de ya, golden dreams were shiny days 
Ba de ya de ya de ya 
Ba de ya de ya de ya 
Ba de ya de ya de ya, de ya 
Ba de ya de ya de ya 
Ba de ya de ya de ya 
Ba de ya de ya de ya, de ya

**Comment by SirVertigo** [comment]
blawar would be proud pepega

**Comment by SirVertigo** [comment]
https://www.youtube.com/watch?v=NdqbI0_0GsM

**Comment by gaavin** [comment]
nice song!
