### ISSUE TITLE
Unbanana instructions?

### ISSUE THREAD

**Issue by jkid291** [team-mercure/mercury#17]
There is no instructions for Unbanana, it wants my Serial number, doesn’t say what format, where it wants it, how it wants it, or if there is a another program to dump it. I could just make a text file with it in it but I would not know where to place it, but this could very well be pointless as it could want it as a .txt, .bin, or whatever else.

**Comment by gaavin** [comment]
this is not an issue please click the star button instead since unbanana has helped you greatly! you are unbanned now!

**Comment by jkid291** [comment]
Homebrew app: shows error
Me: reports error, am not able to inject new cert
gaavin: YoUr UnBaNnEd
