### ISSUE TITLE
cmon guys i know you have the popcorn

### ISSUE THREAD

**Issue by UnobtaniumGamer** [team-mercure/mercury#4]
give it to m e pleas e

**Comment by monkeyman4412** [comment]
Guv me popcorn too. This seems like fun

**Comment by UnobtaniumGamer** [comment]
we crusade for our slaughtered prodinfo and our popcorn

**Comment by TheRealRitzer** [comment]
hi can i have some too

**Comment by monkeyman4412** [comment]
Yes you may once we get it!
