### ISSUE TITLE
illegal activities of gayvin

### ISSUE THREAD

**Issue by GitHubNewsGitGudOfficial** [team-mercure/mercury#45]
![gayvin](https://user-images.githubusercontent.com/53665451/62416996-a5171080-b64d-11e9-9cd4-08bd3f67b908.png)
Yesterday, at the local t*@#?! store The Legendary Wild **GAYVIN** was spotted.
**GAYVIN** was stealing popcorn weeds which is a legendary crime. **GAYVIN'S** crime activities include;

Instructions not clear for CFW team-mercure/mercury one anonymous person has reported that his master sword was stuck to the switch, he died an honorable death.

Denying people popcorn.

Stealing Popcorn Weed as mentioned above

Using g+ icon as Profile Picture, illegal!

Most importantly Online harrasing

+More that we can't list because his crime records pass 1000+

We As GitGudNews (GGN) want Phoneix Wright to come and sue this abomination if you support us just support we can feel it. We are a Family Friendly News Source so you can trust us, this has been GGN see you tomorrow!

EDIT: Even GBATemp has archived the thread because Gayvin does what legaldont!

**Comment by gaavin** [comment]
i don't care
